# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
import jardins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogoservico", "0001_initial"),
        ("unidadee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jardins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=jardins.models.generate_id_random, unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("area", models.FloatField()),
                (
                    "vegetacao",
                    models.CharField(
                        choices=[
                            ("Grama", "Grama"),
                            ("Mata nativa", "Mata nativa"),
                            ("Mata de eucalipto", "Mata de eucalipto"),
                            ("Bosque", "Bosque"),
                            ("Cerca viva", "Cerca viva"),
                            ("Bosque de plantio vivo", "Bosque de plantio vivo"),
                            ("Jardim", "Jardim"),
                            ("Palmeiras", "Palmeiras"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "terreno",
                    models.CharField(
                        choices=[
                            ("Talude", "Talude"),
                            ("Área plana concretada", "Área plana concretada"),
                            ("Área plana não concretada", "Área plana não concretada"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                    ),
                ),
                (
                    "periodicidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mensal", "Mensal"),
                            ("Semanal", "Semanal"),
                            ("Quinzenal", "Quinzenal"),
                            ("Bimestral", "Bimestral"),
                            ("Semestral", "Semestral"),
                            ("Trimestral", "Trimestral"),
                        ],
                        default="",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "servicos_na_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicooriginal",
                        to="catalogoservico.catalogoservicos",
                    ),
                ),
                (
                    "unidade_jardim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localidadeoriginal",
                        to="unidadee.localidade",
                    ),
                ),
            ],
            options={
                "unique_together": {("nome", "unidade_jardim", "vegetacao", "terreno")},
            },
        ),
    ]
