# Generated by Django 5.0.6 on 2024-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jardins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jardins",
            name="vegetacao",
            field=models.CharField(
                choices=[
                    ("Grama", "Grama"),
                    ("Mata nativa", "Mata nativa"),
                    ("Mata de eucalipto", "Mata de eucalipto"),
                    ("Bosque", "Bosque"),
                    ("Cerca viva", "Cerca viva"),
                    ("Bosque de plantio vivo", "Bosque de plantio vivo"),
                    ("Jardim", "Jardim"),
                    ("Palmeiras", "Palmeiras"),
                    ("Outros Pisos", "Outros Pisos"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
