# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
        ("unidadee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiltroTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datafim", models.DateField(blank=True, null=True)),
                ("datastart", models.DateField(blank=True, null=True)),
                (
                    "localidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localidadefiltro",
                        to="unidadee.localidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidadefiltro",
                        to="unidadee.unidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FiltroTableManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datafim", models.DateTimeField(blank=True, null=True)),
                ("datastart", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "tipo_manutencao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Preventiva", "Preventiva"),
                            ("Corretiva", "Corretiva"),
                            ("Detectiva", "Detectiva"),
                            ("Proativa", "Proativa"),
                            ("De Oportunidade", "De Oportunidade"),
                            ("Planejada", "Planejada"),
                            ("Autônoma", "Autônoma"),
                            ("Condicional", "Condicional"),
                            ("De Emergência", "De Emergência"),
                            ("De Rotina", "De Rotina"),
                        ],
                        default="",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresafiltromanutencao",
                        to="empresa.empresa",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidadefiltromanutencao",
                        to="unidadee.unidade",
                    ),
                ),
            ],
        ),
    ]
