# Generated by Django 5.0.6 on 2024-06-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
        ("empresa", "0004_alter_empresa_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="filtrotable",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unidadefiltro",
                to="empresa.empresa",
            ),
        ),
    ]
