# Generated by Django 5.0.6 on 2024-06-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_alter_empresa_nome"),
        ("gestor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestor",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empresaorigem",
                to="empresa.empresa",
            ),
        ),
    ]
