# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
import materiais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materiais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=materiais.models.generate_id_random, unique=True
                    ),
                ),
                ("material", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Fertilizante", "Fertilizante"),
                            ("pesticida", "pesticida"),
                            ("Formicida", "Formicida"),
                            ("Adubos", "Adubos"),
                            ("Herbicida", "Herbicida"),
                            ("Fungicida", "Fungicida"),
                            ("Inseticida", "Inseticida"),
                            ("Condicionadores de Solo", "Condicionadores de Solo"),
                            ("Inoculantes", "Inoculantes"),
                            ("Mulching", "Mulching"),
                            ("Anti - caracóis e lesmas", "Anti - caracóis e lesmas"),
                            ("Bioestimulantes", "Bioestimulantes"),
                            ("Adjuvantes", "Adjuvantes"),
                        ],
                        default="",
                        max_length=60,
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        choices=[
                            ("Sache", "Sache"),
                            ("KG", "KG"),
                            ("Refil", "Refil"),
                            ("Litros", "Litros"),
                            ("Pacote", "Pacote"),
                            ("Barra", "Barra"),
                            ("Galões ", "Galões "),
                            ("Peças", "Peças"),
                            ("Unidades", "Unidades"),
                            ("Potes", "Potes"),
                            ("Tubos", "Tubos"),
                            ("Fardos", "Fardos"),
                            ("Sacos", "Sacos"),
                        ],
                        default="",
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "categoria", "consumo", "empresa")},
            },
        ),
    ]
