# Generated by Django 5.0.6 on 2024-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiais",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fertilizante", "Fertilizante"),
                    ("pesticida", "pesticida"),
                    ("Formicida", "Formicida"),
                    ("Adubos", "Adubos"),
                    ("Herbicida", "Herbicida"),
                    ("Fungicida", "Fungicida"),
                    ("Inseticida", "Inseticida"),
                    ("Condicionadores de Solo", "Condicionadores de Solo"),
                    ("Inoculantes", "Inoculantes"),
                    ("Mulching", "Mulching"),
                    ("Anti - caracóis e lesmas", "Anti - caracóis e lesmas"),
                    ("Bioestimulantes", "Bioestimulantes"),
                    ("Adjuvantes", "Adjuvantes"),
                ],
                default="",
                max_length=60,
                null=True,
            ),
        ),
    ]
