# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("colaborador", "0001_initial"),
        ("gerente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="gerente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestororigem",
                to="gerente.gerente",
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="colaborador_set", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="colaborador_permissions_set",
                to="auth.permission",
            ),
        ),
    ]
