# Generated by Django 5.0.6 on 2024-05-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaborador", "0002_initial"),
        ("gerente", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="gerente",
        ),
        migrations.AddField(
            model_name="colaborador",
            name="gerente",
            field=models.ManyToManyField(
                related_name="gestororigem", to="gerente.gerente"
            ),
        ),
    ]
