# Generated by Django 5.0.6 on 2024-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaborador", "0004_alter_colaborador_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
