# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
import servico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogoservico", "0001_initial"),
        ("colaborador", "0001_initial"),
        ("equipamento", "0001_initial"),
        ("ferramenta", "0001_initial"),
        ("jardins", "0001_initial"),
        ("materiais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=servico.models.generate_id_random, unique=True
                    ),
                ),
                ("descricao_servico", models.TextField(max_length=100)),
                ("data_inicio", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Agendado", "Agendado"),
                            ("Cancelado", "Cancelado"),
                            ("Em andamento", "Em andamento"),
                            ("Concluido", "Concluido"),
                        ],
                        default="Agendado",
                        max_length=60,
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="media/%Y/%m/%d/")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areaoriginais",
                        to="jardins.jardins",
                    ),
                ),
                (
                    "colaboradores_escalados",
                    models.ManyToManyField(
                        related_name="colaboradoresoriginais",
                        to="colaborador.colaborador",
                    ),
                ),
                (
                    "servicos_escalados",
                    models.ManyToManyField(
                        related_name="catalogoservicooriginal",
                        to="catalogoservico.catalogoservicos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FatoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora_chegada_na_area", models.DateTimeField()),
                ("data_hora_retorno_area", models.DateTimeField()),
                ("quantidade", models.FloatField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Proprio", "Proprio"),
                            ("Terceirizado", "Terceirizado"),
                        ],
                        default="Proprio",
                        max_length=60,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboradorservico",
                        to="colaborador.colaborador",
                    ),
                ),
                (
                    "equipamentos_usados",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipamentodisponiveloriginal",
                        to="equipamento.equipamentodisponivel",
                    ),
                ),
                (
                    "ferramentas_usados",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ferramentadisponiveloriginal",
                        to="ferramenta.ferramentadisponivel",
                    ),
                ),
                (
                    "material_usado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiaisusados",
                        to="materiais.materiais",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicooriginal",
                        to="servico.servicos",
                    ),
                ),
            ],
        ),
    ]
