# Generated by Django 5.0.6 on 2024-05-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicos",
            name="data_conclusao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
