# Generated by Django 5.0.6 on 2024-05-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0002_servicos_data_conclusao"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicos",
            name="foto_inicio",
            field=models.ImageField(blank=True, upload_to="media/%Y/%m/%d/"),
        ),
    ]
