# Generated by Django 5.0.6 on 2024-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0005_alter_servicos_tipo_servico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicos",
            name="tipo_servico",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular"),
                    ("Extra", "Extra"),
                    ("Outros", "Outros"),
                ],
                default="Regular",
                max_length=60,
            ),
        ),
    ]
