# Generated by Django 5.0.6 on 2024-06-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogoservico", "0001_initial"),
        ("servico", "0006_alter_servicos_tipo_servico"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatoservico",
            name="servico_aplicado",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogoservico.catalogoservicos",
            ),
            preserve_default=False,
        ),
    ]
