# Generated by Django 5.0.6 on 2024-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0007_fatoservico_servico_aplicado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicos",
            name="foto",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="media/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="servicos",
            name="foto_inicio",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="media/%Y/%m/%d/"
            ),
        ),
    ]
