# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
import equipamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoEquipamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=equipamento.models.generate_id_random, unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                ("vida_util_meses", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresacatalogoequipamento",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "unique_together": {("nome", "marca", "empresa")},
            },
        ),
        migrations.CreateModel(
            name="EquipamentoDisponivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=equipamento.models.generate_id_random, unique=True
                    ),
                ),
                ("data_aquisicao", models.DateField()),
                ("data_desmobilizacao", models.DateField(blank=True, null=True)),
                ("matricula", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Próprio", "Próprio"),
                            ("Terceirizado", "Terceirizado"),
                        ],
                        default="",
                        max_length=60,
                    ),
                ),
                (
                    "catalogo_equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogoequipamentooriginal",
                        to="equipamento.catalogoequipamentos",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresaequipamentoorigem",
                        to="empresa.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManutencaoEquipamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=equipamento.models.generate_id_random, unique=True
                    ),
                ),
                ("data_hora_inicio", models.DateTimeField()),
                ("data_hora_fim", models.DateTimeField()),
                ("descricao_servico", models.TextField()),
                ("descricao_motivo", models.TextField()),
                (
                    "tipo_manutencao",
                    models.CharField(
                        choices=[
                            ("Preventiva", "Preventiva"),
                            ("Corretiva", "Corretiva"),
                            ("Detectiva", "Detectiva"),
                            ("Proativa", "Proativa"),
                            ("De Oportunidade", "De Oportunidade"),
                            ("Planejada", "Planejada"),
                            ("Autônoma", "Autônoma"),
                            ("Condicional", "Condicional"),
                            ("De Emergência", "De Emergência"),
                            ("De Rotina", "De Rotina"),
                        ],
                        default="",
                        max_length=60,
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipamento.equipamentodisponivel",
                    ),
                ),
            ],
        ),
    ]
