# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
import empresa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("unidadee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=empresa.models.generate_id_random, unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("razao_social", models.CharField(max_length=100)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidadeorigem",
                        to="unidadee.unidade",
                    ),
                ),
            ],
        ),
    ]
