# Generated by Django 5.0.6 on 2024-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
        ("unidadee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=models.CharField(max_length=18),
        ),
        migrations.AlterUniqueTogether(
            name="empresa",
            unique_together={("cnpj", "unidade")},
        ),
    ]
