# Generated by Django 5.0.6 on 2024-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_alter_empresa_cnpj_alter_empresa_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="tipo_empresa",
            field=models.CharField(
                choices=[
                    ("Jardinagem", "Jardinagem"),
                    ("Limpeza predial", "Limpeza predial"),
                ],
                default="Jardinagem",
                max_length=60,
            ),
        ),
    ]
