# Generated by Django 5.0.6 on 2024-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_alter_empresa_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
