# Generated by Django 5.0.6 on 2024-05-26 01:36

import django.db.models.deletion
import unidadee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=unidadee.models.generate_id_random, unique=True
                    ),
                ),
                ("unidade", models.CharField(max_length=100, unique=True)),
                ("link", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Localidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_random",
                    models.IntegerField(
                        default=unidadee.models.generate_id_random_localidade,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Mobilizado", "Mobilizado"),
                            ("Desmobilizado", "Desmobilizado"),
                            ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                        ],
                        default="Mobilizado",
                        max_length=60,
                    ),
                ),
                (
                    "unidadeoriginial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidadeoriginal",
                        to="unidadee.unidade",
                    ),
                ),
            ],
            options={
                "unique_together": {("nome", "unidadeoriginial")},
            },
        ),
    ]
