# Generated by Django 5.0.6 on 2024-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unidadee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="localidade",
            name="negocio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mobilizado", "Mobilizado"),
                    ("Desmobilizado", "Desmobilizado"),
                    ("Desmobilizacao Permanente", "Desmobilizacao Permanente"),
                ],
                default="Industrial",
                max_length=60,
                null=True,
            ),
        ),
    ]
