# Generated by Django 5.0.6 on 2024-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unidadee", "0002_localidade_negocio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localidade",
            name="negocio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Industrial", "Industrial"),
                    ("Florestal", "Florestal"),
                    ("Outros", "Outros"),
                ],
                default="Industrial",
                max_length=60,
                null=True,
            ),
        ),
    ]
