# Generated by Django 5.0.6 on 2024-06-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unidadee", "0003_alter_localidade_negocio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="localidade",
            unique_together={("nome", "unidadeoriginial", "negocio")},
        ),
    ]
